### ISSUE TITLE
[0.62.1][issue][rift] crash while playing ai

### ISSUE THREAD

**Issue by ab050505** [ForFunLabs/ElevenPublicBugsAndAsks#219] opened 2019-12-10 19:34 UTC
logs:
https://drive.google.com/file/d/1LulYpQ6NX0YiIvcsVPdoGHAGEfpOnI-E/view?usp=sharing

**Comment by ab050505** [comment] 2019-12-11 13:35
happened again now, within a few minutes of launching the game (not much else running on the pc)
logs:
https://drive.google.com/file/d/104WxbkrRwLeimQhhcY2pmJ5m0_SdYlnC/view?usp=sharing

**Comment by ab050505** [comment] 2019-12-11 15:55
(fwiw, there was a windows update pending)

**Comment by carrotstien** [comment] 2020-01-09 04:20
ugh... i don't know if it's unity itself doing something wrong, or the physics code. Do you remember anything you were doing at this moment?

Literally the only way to find this is to play while c++ debugging is enabled, and just hope to hit it. 
"ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF712CE11F2)"

isn't a very catchable error otherwise :(

Do you remember maybe...the ball hit something in particular before the crash?



Either way, the first crash was caused by something different than the second. I'm not sure what the first one was caused by either...but it might be possible that my current push will prevent that from happening.

**Comment by ab050505** [comment] 2020-01-09 06:33
i'm afraid i don't remember what exactly i (or ai) was doing just before the crashes (but i'm sure nothing extraordinary had happened before either crash). thought i'd post those logs anyway just in case there was some obvious issue. will try to post a recording too next time.

**Comment by carrotstien** [comment] 2020-01-09 06:54
i'd like to keep this open so i can hold a reference to crash logs

**Comment by ab050505** [comment] 2020-01-09 07:10
sure

**Comment by dukeoflegs** [comment] 2024-06-25 21:53
Closing, no longer an issue.

**Closed as completed by dukeoflegs** 2024-06-25 21:53 UTC
Labels: crash
