### ISSUE TITLE
[bug] On some hits, paddle goes through ball and haptics do not work

### ISSUE THREAD

**Issue by Hero-Over** [ForFunLabs/ElevenPublicBugsAndAsks#143] opened 2019-09-29 21:23 UTC
This is seemingly caused by frame drops. Occurs much more frequently with higher ping games, but also occurs randomly in single player.

Valve Index. SteamVR.

**Comment by carrotstien** [comment] 2020-01-05 21:23
unable to reproduce...until we have replays working, it'd be very hard to even debug this. so closing for now

**Closed as completed by carrotstien** 2020-01-05 21:23 UTC
