### ISSUE TITLE
[Quest][Bug] Quadrant losing randomly points

### ISSUE THREAD

**Issue by Talwar85** [ForFunLabs/ElevenPublicBugsAndAsks#33] opened 2019-06-04 01:22 UTC
In quadrant after you lost a live there is a random chance that you will lose another point afterwards immediatly when you hit the ball.

**Comment by carrotstien** [comment] 2019-06-06 05:45
I tried to do this..hasn't happened. Does it still happen to you?

**Comment by carrotstien** [comment] 2019-06-13 05:46
still unable to reproduce..closing for now

**Closed as completed by carrotstien** 2019-06-13 05:46 UTC
