### ISSUE TITLE
Duplicate in-game controller bug

### ISSUE THREAD

**Issue by StownieDaze** [ForFunLabs/ElevenPublicBugsAndAsks#76] opened 2019-07-11 15:02 UTC
when playing online my opponent turned his controller off & then on again but rather than it disappearing and reappearing. there was 1 controller frozen at the point where it powered off and another one spawned where his controller actually was which became his hand that he could move about while the other duplicate controller remained frozen in time.

**Comment by carrotstien** [comment] 2019-08-06 18:21
closing a duplicate of #82

**Closed as completed by carrotstien** 2019-08-06 18:21 UTC
