### ISSUE TITLE
Ball machine randomly shoots ball anywhere except on table

### ISSUE THREAD

**Issue by Talwar85** [ForFunLabs/ElevenPublicBugsAndAsks#25] opened 2019-06-03 12:51 UTC
Hi,

I changed the sliders a bit from the ball machine, 
but afterwards the balls were shot backwards, left or right from the table but never on the table. 

Even a slight change in the sliders had various negative results.

**Comment by carrotstien** [comment] 2019-06-03 13:17
some of the sliders are "spread" or randomness. It is likely this was the cause. We need to add some smart controls on the slider so that the ball machine at least never shoots outside of the boundary of the table (unless maybe if you press a check box somewhere to allow it)

**Comment by Talwar85** [comment] 2019-06-03 21:29
@carrotstien How about just visual vertical lines on the sliding machine? So you are able to selfcheck if you are in boundaries. 

Or make the horizontal line for example: grey_green_grey

**Comment by carrotstien** [comment] 2019-08-14 11:10
ball machine completely revamped, so closing

**Closed as completed by carrotstien** 2019-08-14 11:10 UTC
Labels: quest, ball machine
