### ISSUE TITLE
Player stats are not updating

### ISSUE THREAD

**Issue by Shlabotnik** [ForFunLabs/ElevenPublicBugsAndAsks#536] opened 2024-10-18 04:15 UTC
My statistics for games played and for my rating have not been updating for a couple of weeks. My ranked games played is stuck at 42 and it should be in the fifties or sixties. My skill rating and ranked games has not changed. Any suggestions? Also...
Thanks for listening

**Comment by carrotstien** [comment] 2024-10-18 15:29
it looks like you are not playing ranked games. Only ranked games affect those stats. 
[Matched_Data.csv](https://github.com/user-attachments/files/17437605/Matched_Data.csv)

**Comment by carrotstien** [comment] 2024-10-18 15:30
![image](https://github.com/user-attachments/assets/1f3fe0ff-5707-4e90-aebc-5a5f9cb12646)

**Comment by Shlabotnik** [comment] 2024-10-18 20:41
How could this happen all of a sudden? I don't believe that I have changed any settings that would cause this. I have assumed that every match I've played was against a ranked opponent. How can I change this? 
I'm still learning this game and I love it. I played for several years at a club in Rhode Island and Eleven TT brings me right back there.

**Comment by carrotstien** [comment] 2024-10-18 20:48
if you are sending a challenge or receiving a challenge, that is an unranked match. An unranked match can follow casual or strict serving rules. The only way you do ranked match is if you click on ranked play and the system matches you up.

though you can also go into a custom room and do a ranked match there - but that involves a room code. 

Are you saying you went through the ranked match matchmaking system and got unranked matches?

**Comment by Shlabotnik** [comment] 2024-10-22 02:44
For some reason I have been getting requests for challenges and I've been accepting them. Didn't realize it would be an unranked match. So the sender must also know that it's an unranked match. Why would players ranked 400-500 points above me want to play an unraked match? Some of them I have played before and I lost almost every match. And loved every minute of it.
  On another issue, I'm having a real problem with my paddle detaching from the right controller. I t happens mostly on forehand smashes when I practice with the AI at the 100 level. The paddle ends up near my face but the controller is back near my hip. I have the targets enabled, as small as they can be and located on the center line. I practice a lot of fast loops shots and forehand smashes. That's when I lose contact with the paddle. With this practice setup I can have rallies of 20 to 40 shots at a time with the AI. Should I expect to have a slow reaction time? I can make misteaks also, so maybe it's me.

Thanks,
Mark

**Comment by carrotstien** [comment] 2024-10-29 20:14
re the first thing - some people just like unranked sometimes. 

re the second thing - that's tracking loss that can be caused by a lot of things - often by bad paddle adapters but sometimes just based on the motion of your swing. It's a hardware level issue. If you want to troubleshoot further, it'd be easier to do on the discord. 

closing this issue.

**Closed as completed by carrotstien** 2024-10-29 20:14 UTC
